edit OWASP Dependency Check workflow

diff --git a/.github/workflows/scan-with-owasp-dependency-check.yml b/.github/workflows/scan-with-owasp-dependency-check.yml
--- a/.github/workflows/scan-with-owasp-dependency-check.yml
+++ b/.github/workflows/scan-with-owasp-dependency-check.yml
@@ -47,3 +47,10 @@ jobs:
         with:
           sarif_file: dependency-check-report.sarif
           category: "Scan-dependencies-code-with-OWASP-Dependency-Check"
+
+      - name: Verify SARIF file
+        run: |
+          if [ ! -f "$OUTPUT_DIR/dependency-check-report.sarif" ]; then
+          echo "Error: SARIF file not found"
+          exit 1
+          fi
